# Use latest Node.js LTS as base
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all source files, including .env generated by GitHub Actions
COPY . .

# Build Next.js app
RUN npm run build

# Production image, smaller size
FROM node:18-alpine AS runner

WORKDIR /app

# Copy package.json and production node_modules
COPY package*.json ./
RUN npm install --production

# Copy built files and public assets from builder stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.env ./.env

# Expose port 3000 (you map it to 80 externally in docker run)
EXPOSE 3000

# Start Next.js in production mode
CMD ["npm", "start"]
