import type { Metadata } from "next";
import { loadStripe } from "@stripe/stripe-js";
import StripeProvider from "./StripeProvider";

const stripePromise = loadStripe("pk_test_51S2wJ5LftZnSCITqn0pN2AZpIuDosea70tdWyyYuIlQHuMWxzEYOFkPtb4y2PWwkYquTQcbkR1gfwsq8pwc2CBQ000ibxy88Df");

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <StripeProvider>
          {children}
        </StripeProvider>
      </body>
    </html>
  );
}
