- name: Deploy on EC2
  uses: appleboy/ssh-action@v0.1.7
  with:
    host: ${{ env.EC2_HOST }}
    username: ${{ env.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      # commands to pull image and restart container
      # Login to ECR
      aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
      docker login --username AWS --password-stdin 043309366307.dkr.ecr.us-east-1.amazonaws.com

      # Pull new Docker image
      docker pull $IMAGE_URI
      docker tag $IMAGE_URI 043309366307.dkr.ecr.us-east-1.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      # Stop and remove old container
      docker stop ${{ env.DOCKER_CONTAINER_NAME }} || true
      docker rm ${{ env.DOCKER_CONTAINER_NAME }} || true

      # Run container using .env file
      docker run -d --restart unless-stopped -p 80:3000 \
        --env-file ${{ env.ENV_FILE_PATH }} \
        --name ${{ env.DOCKER_CONTAINER_NAME }} \
        043309366307.dkr.ecr.us-east-1.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
