name: CI/CD to EC2

on:
  push:
    branches: [ main, master ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: my-ai-agent
  EC2_HOST: 54.152.182.10
  EC2_USER: ec2-user
  DOCKER_CONTAINER_NAME: my-ai-agent

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci --legacy-peer-deps
      - run: npm test --silent || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}`
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create .env file
        run: |
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" >> .env
          echo "STRIPE_INTRO_PRICE_ID=${{ secrets.STRIPE_INTRO_PRICE_ID }}" >> .env
          echo "STRIPE_NORMAL_PRICE_ID=${{ secrets.STRIPE_NORMAL_PRICE_ID }}" >> .env
          echo "STRIPE_ADD_LOCATION_PRICE_ID=${{ secrets.STRIPE_ADD_LOCATION_PRICE_ID }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "NINJAS_API_KEY=${{ secrets.NINJAS_API_KEY }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env

      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

          docker build \
            --build-arg STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg NINJAS_API_KEY=${{ secrets.NINJAS_API_KEY }} \
            --build-arg STRIPE_ADD_LOCATION_PRICE_ID=${{ secrets.STRIPE_ADD_LOCATION_PRICE_ID }} \
            --build-arg STRIPE_INTRO_PRICE_ID=${{ secrets.STRIPE_INTRO_PRICE_ID }} \
            --build-arg STRIPE_NORMAL_PRICE_ID=${{ secrets.STRIPE_NORMAL_PRICE_ID }} \
            --build-arg TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
            --build-arg TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
            -t $IMAGE_URI .

          docker tag $IMAGE_URI $IMAGE_URI
          docker push $IMAGE_URI

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if ! command -v aws &> /dev/null; then
              sudo yum install -y awscli
            fi

            aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
              docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

            if docker ps -a --format '{{.Names}}' | grep -Eq "^${{ env.DOCKER_CONTAINER_NAME }}$"; then
              docker stop ${{ env.DOCKER_CONTAINER_NAME }}
              docker rm ${{ env.DOCKER_CONTAINER_NAME }}
            fi

            docker run -d \
              --restart unless-stopped \
              -p 80:3000 \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
              -e NINJAS_API_KEY="${{ secrets.NINJAS_API_KEY }}" \
              -e STRIPE_ADD_LOCATION_PRICE_ID="${{ secrets.STRIPE_ADD_LOCATION_PRICE_ID }}" \
              -e STRIPE_INTRO_PRICE_ID="${{ secrets.STRIPE_INTRO_PRICE_ID }}" \
              -e STRIPE_NORMAL_PRICE_ID="${{ secrets.STRIPE_NORMAL_PRICE_ID }}" \
              -e TWILIO_ACCOUNT_SID="${{ secrets.TWILIO_ACCOUNT_SID }}" \
              -e TWILIO_AUTH_TOKEN="${{ secrets.TWILIO_AUTH_TOKEN }}" \
              --name ${{ env.DOCKER_CONTAINER_NAME }} \
              ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

            echo "✅ Deployment completed successfully!"
  